#:schema node_modules/wrangler/config-schema.json
name = "envirosagro-blockchain"
compatibility_date = "2024-11-01"

[assets]
directory = "./dist"

[vars]
# Environment variables like API_KEY are typically managed in the Cloudflare Dashboard
