#:schema node_modules/wrangler/config-schema.json
name = "envirosagro"
compatibility_date = "2026-02-15"
pages_build_output_dir = "dist"

[vars]
# Environment variables like API_KEY are typically managed in the Cloudflare Dashboard,
# but can be referenced here if using Wrangler for local development.
